const ROLE_ADMIN = 1;
const ROLE_USER = 2;

const STATUS_ENABLED = 1;
const STATUS_DISABLED = 2;

const ROLE_PROJECT_MANAGER = 1;
const ROLE_DEVELOPER = 2;

module.exports = {
  ROLE_ADMIN,
  ROLE_USER,
  STATUS_ENABLED,
  STATUS_DISABLED,
  ROLE_PROJECT_MANAGER,
  ROLE_DEVELOPER,
};
